[features]
seeds = false
skip-lint = false
[programs.localnet]
solanagrid = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/sarahagarrat/.config/solana/id.json"

[scripts]
test = "node tests/solanagrid.js"
